# Configuration eth1 / Ansible playbook
# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:

  - name: Configuration de VM2/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.132/28
      
  - name: Configuration de la route vers LAN3 via VM1
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4: 172.16.2.144/28  172.16.2.131
      state: present

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"

  - name: Configuration de VM2/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip4: 172.16.2.162/28

  - name: Configuration de la route vers LAN4 via VM3
    community.general.nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      routes4: 172.16.2.176/28  172.16.2.163
      state: present

  - name: Activation explicite de la configuration eth2
    shell: nmcli con up "eth2 via ansible"

# Activer le routage
  - name: Activation du routage IPv4
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      sysctl_set: yes

  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true
