# Configuration eth1 / Ansible playbook
# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:

# Configurations Réseaux
  - name: Configuration de VM3-6/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip6: fc00:1234:2::36/64

  - name: Configuration de la route vers LAN1-6 via VM2-6
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes6: fc00:1234:1::/64 fc00:1234:2::26
      state: present

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"

  - name: Configuration de VM3-6/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present

      autoconnect: true
      ip4: 172.16.2.186/28

  - name: Configuration de la route vers LAN2, LAN1, LAN3 via VM2
    community.general.nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      routes4:
        - 172.16.2.160/28 172.16.2.183
        - 172.16.2.128/28 172.16.2.183
        - 172.16.2.144/28 172.16.2.183
      state: present

  - name: Activation explicite de la configuration eth2
    shell: nmcli con up "eth2 via ansible"

  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true

  - name: Accès via default gateway et DNS
    shell: dhclient eth0

  - name: Installer inetd
    shell: apt install inetutils-inetd

  - name: Delete default
    shell: ip route del default

  - name: launch inetd
    shell: service inetutils-inetd start

  - name: restart inetd
    shell: service inetutils-inetd restart



