# Configuration eth1 / Ansible playbook
# RAPPEL: eth0 est à vagrant, ne pas y toucher

- hosts: localhost
  remote_user: root
  tasks:

  - shell: nmcli connection del "Wired connection 1"
    ignore_errors: true

  - name: Configuration de VM3/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.183/28

  - name: Configuration de la route vers LAN3 et tun0 via tun0
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4:
        - 172.16.2.144/28 172.16.2.186
        - 172.16.2.0/28 172.16.2.186
      state: present

  - name: Activation explicite de la configuration eth1
    shell: nmcli con up "eth1 via ansible"



  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true
